services:
  # =======================
  # FRONTEND VUE
  # =======================
  vue-app:
    build: ./Fronted
    container_name: vue_app
    ports:
      - "5173:5173"
    volumes:
      - ./Fronted:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - carte
      - app

  # =======================
  # SERVICE MAP (CARTE)
  # =======================
  carte:
    build:
      context: ./Map
    container_name: carte_service
    ports:
      - "3000:8080"
    volumes:
      - ./Map/data:/data
      - ./Map/styles:/data/styles
      - ./Map/fonts:/data/fonts
    restart: unless-stopped

  # =======================
  # BACKEND LARAVEL API
  # =======================
  app:
    build:
      context: ./Backend
    container_name: laravel_app_api
    working_dir: /var/www/html
    volumes:
      - ./Backend/laravel_api:/var/www/html
      - ./Backend/laravel_api/storage/logs:/var/www/html/storage/logs
    ports:
      - "8000:80"
    depends_on:
      - postgres
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: secret

    command: >
      sh -c "
      chown -R www-data:www-data /var/www/html &&
      chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
      apache2-foreground
      "

  # =======================
  # DATABASE POSTGRESQL
  # =======================
  postgres:
    image: postgres:14
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# =======================
# VOLUMES
# =======================
volumes:
  postgres_data:
